# Generated by Django 2.2.7 on 2021-11-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherItemsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость первого кв.м.')),
                ('next_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость последующих кв.м.')),
            ],
            options={
                'verbose_name': 'Стоимость хранения другого',
                'verbose_name_plural': 'Стоимость хранения другого',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
                ('phone_number', models.CharField(blank=True, default='', max_length=256, verbose_name='Номер телефона заказчика')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия заказчика')),
                ('passport_id', models.CharField(max_length=11, verbose_name='Паспортные данные заказчика')),
                ('birthday', models.DateField(verbose_name='Дата рождения заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='SeasonalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('лыжи', 'лыжи'), ('сноуборд', 'сноуборд'), ('велосипед', 'велосипед'), ('колеса', 'колеса')], max_length=256, verbose_name='Наименование вещи')),
            ],
            options={
                'verbose_name': 'Сезонная вещь',
                'verbose_name_plural': 'Сезонные вещи',
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование склада')),
                ('address', models.TextField(verbose_name='Адрес склада')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='SeasonalItemsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость хранения в неделю')),
                ('month_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость хранения в месяц')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.SeasonalItems', verbose_name='Наименование вещи')),
            ],
            options={
                'verbose_name': 'Стоимость хранения сезонной вещи',
                'verbose_name_plural': 'Стоимость хранения сезонной вещи',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_type', models.CharField(choices=[('сезонные вещи', 'сезонные вещи'), ('другое', 'другое')], max_length=256, verbose_name='Что хранить')),
                ('cell_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Габаритность ячейки')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество вещей')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('start_date', models.DateField(verbose_name='Дата бронирования с')),
                ('end_date', models.DateField(verbose_name='Дата бронирования по')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Customers', verbose_name='Заказчик')),
                ('seasonal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.SeasonalItems', verbose_name='Сезонная вещь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
