# Generated by Django 2.2.7 on 2021-11-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20211118_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='warehouse',
        ),
    ]
