# Generated by Django 2.2.7 on 2021-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_auto_20211121_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR код'),
        ),
    ]
