# Generated by Django 2.2.7 on 2021-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_orders_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrs', verbose_name='QR код'),
        ),
    ]
